import re
import requests
from urllib.parse import quote

class EVEApi:
    def __init__(self, host, username, password, https=False, verify_ssl=False):
        clean = re.sub(r"^https?://", "", host.strip()).rstrip("/")
        self.base = ("https://" if https else "http://") + clean
        self.username = username
        self.password = password
        self.session = requests.Session()
        self.session.verify = verify_ssl

    def _path(self, lab):
        return quote(lab.lstrip("/"), safe="/")

    def request(self, method, endpoint, **kwargs):
        response = self.session.request(method, self.base + "/api" + endpoint, timeout=30, **kwargs)
        try:
            data = response.json()
        except Exception:
            data = {"status": "error", "message": response.text}
        if not response.ok or data.get("status") not in (None, "success"):
            raise RuntimeError(f"EVE API {method} {endpoint}: HTTP {response.status_code}: {data}")
        return data

    def login(self):
        response = self.session.post(
            self.base + "/api/auth/login",
            json={"username": self.username, "password": self.password},
            timeout=15,
        )
        if not response.ok:
            raise RuntimeError(f"EVE API login failed: HTTP {response.status_code}")
        data = response.json()
        if data.get("status") != "success":
            raise RuntimeError(str(data))
        return data

    def create_folder(self, parent, name):
        return self.request("POST", "/folders", json={"path": parent, "name": name})

    def create_lab(self, folder, name, description="CCNA 200-301 lab"):
        return self.request("POST", "/labs", json={
            "path": folder, "name": name, "version": "4",
            "author": "CCNA EVE Lab Builder",
            "description": description,
            "body": "Generated by CCNA EVE Lab Builder V4",
        })

    def lab_path(self, folder, name):
        return folder.rstrip("/") + "/" + name + ".unl"

    def get_lab(self, lab):
        return self.request("GET", "/labs/" + self._path(lab))

    def add_node(self, lab, node):
        return self.request("POST", f"/labs/{self._path(lab)}/nodes", json=node)

    def nodes(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes")

    def node(self, lab, node_id):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes/{node_id}")

    def interfaces(self, lab, node_id):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes/{node_id}/interfaces")

    def add_network(self, lab, name, left="50%", top="50%", net_type="bridge"):
        return self.request("POST", f"/labs/{self._path(lab)}/networks", json={
            "type": net_type, "name": name, "left": left, "top": top
        })

    def networks(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/networks")

    def links(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/links")

    def topology(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/topology")

    def start_all(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes/start")

    def stop_all(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes/stop")

    def wipe_all(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes/wipe")

    def export_all(self, lab):
        return self.request("GET", f"/labs/{self._path(lab)}/nodes/export")

    def connect_interface_experimental(self, lab, node_id, interface_id, network_id):
        return self.request(
            "PUT",
            f"/labs/{self._path(lab)}/nodes/{node_id}/interfaces",
            json={str(interface_id): str(network_id)},
        )
